#!/bin/bash
# Run by typing '. setup', NOT './setup'

# Install Virtualenv
pip install virtualenv

# Create Virtualenv
virtualenv flask

# Activate Virtualenv
source flask/bin/activate

# Install Flask inside Virtualenv
pip install flask

# Make activate set environment variable
echo -e "\n# Custom environment variable for Flask" >> flask/bin/activate
echo -e "export FLASK_APP=\"app.py\"" >> flask/bin/activate

# Deactivate Virtualenv
deactivate
